[build]
  command = "yarn build"
  publish = ".output/public"  # This should point to the directory with your built static assets
  functions = ".output/server"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200
